INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '24', N'৩২ মিনিট ২৪ ঘণ্টা', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '29', N'৪৬ মিনিট ২৪ ঘণ্টা', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '39', N'৫৫ মিনিট ২ দিন', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '49', N'৭৫ মিনিট ২ দিন', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '59', N'৭০ মিনিট ৩ দিন', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '69', N'৭০ মিনিট ৫ দিন', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '79', N'১০০ মিনিট ৫ দিন', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '99', N'১০৫ মিনিট ৭দিন', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '119', N'১৬০ মিনিট ৭ দিন', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '139', N'২২০ মিনিট ৭ দিন', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '149', N'১৫০ মিনিট ৩০ দিন', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '159', N'২৫০ মিনিট ৭দিন', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '169', N'১৭৫ মিনিট ৩০দিন', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '189', N'২৪০ মিনিট ১৫ দিন', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '199', N'২১০ মিনিট ৩০ দিন', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '239', N'২৭০ মিনিট ৩০ দিন', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '289', N'৩৯০ মিনিট ৩০ দিন', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '319', N'৪৭৫ মিনিট ৩০ দিন', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '409', N'৬৪০ মিনিট ৩০ দিন', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '496', N'৩০০ মিনিট ৩০ দিন', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '509', N'৮০০ মিনিট ৩০ দিন', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '639', N'১০০০ মিনিট ৩০ দিন', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '796', N'৫০০ মিনিট ৩০ দিন', 'false', '0');
INSERT INTO [dbo].[topupdeals] ([operator], [dealtype], [amount], [description], [is_cash_back], [cash_back]) VALUES ('robi', '3', '989', N'১৫০০ মিনিট ১৫০ দিন', 'false', '0');
